version: 2
updates:
  - package-ecosystem: docker
    directory: /images/ml-base
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /images/base
    schedule:
      interval: weekly
    labels:
      - dependencies
